config/routes.rb
Rails.application.routes.draw do
  resources :crops
  resources :coconut1s
  resources :coffee1s
  resources :rice3s
  resources :rice2s
  resources :rice1s
  root to: 'crops#index'
  devise_for :users
  resources :plants
  resources :ratios  
end

app/models/ratio.rb
class Ratio < ApplicationRecord
end

app/controllers/ratios_controller.rb
class RatiosController < ApplicationController
  before_action :set_ratio, only: [:show, :edit, :update, :destroy]

  def index
    # @ratios = Ratio.where
    @ratios = Ratio.all.group_by(&:name)
  end

  # GET /ratios/1
  # GET /ratios/1.json
  def show
  end

  # GET /ratios/new
  def new
    @ratio = Ratio.new
  end

  # GET /ratios/1/edit
  def edit
  end

  # POST /ratios
  # POST /ratios.json
  def create
    @ratio = Ratio.new(ratio_params)

    respond_to do |format|
      if @ratio.save
        format.html { redirect_to @ratio, notice: 'Ratio was successfully created.' }
        format.json { render :show, status: :created, location: @ratio }
      else
        format.html { render :new }
        format.json { render json: @ratio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratios/1
  # PATCH/PUT /ratios/1.json
  def update
    respond_to do |format|
      if @ratio.update(ratio_params)
        format.html { redirect_to @ratio, notice: 'Ratio was successfully updated.' }
        format.json { render :show, status: :ok, location: @ratio }
      else
        format.html { render :edit }
        format.json { render json: @ratio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratios/1
  # DELETE /ratios/1.json
  def destroy
    @ratio.destroy
    respond_to do |format|
      format.html { redirect_to ratios_url, notice: 'Ratio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ratio
      @ratio = Ratio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ratio_params
      params.fetch(:ratio, {})
    end
end

app/views/ratios/_form.html.slim
= simple_form_for(@ratio) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs

  .form-actions
    = f.button :submit

app/views/ratios/_ratio.html.slim
.card.shadow.zoom-xs.mb-3
  /= ratio.first
  = ratio.select{ |r| r.first.id}
  /= link_to ratio.select{ |r| r.first}
    /.text-center
      = image_tag ratio.first.photo, class: "img-fluid rounded"
    .card-footer.text-muted
      h4 
      .small
        /.d-flex.justify-content-end.flex-wrap.pb-2
          = ratio.name
      .text-right
        /small = ratio.updated_at.strftime("%m/%d/%y at %l:%M %p")

        

app/views/ratios/edit.html.slim
h1 Editing ratio

== render 'form'

=> link_to 'Show', @ratio
'|
=< link_to 'Back', ratios_path

app/views/ratios/index.html.slim
.px-4
  .row
    .col-12.col-lg-3
      .pt-3.pb-1
        h1 Ratios
      .pb-2
      // FILTER BUTTONS
      .pb-2.d-flex.justify-content-between.flex-wrap
    // HALF    
    .col-12.col-lg-9
      /= line_chart Ratio.group(:month).count
      = bar_chart Ratio.group(:month).sum(:price)
      /.card-columns
        /= render @ratios
      = render partial: 'ratio', collection: @ratios
      

app/views/ratios/new.html.slim
h1 New ratio

== render 'form'

= link_to 'Back', ratios_path

app/views/ratios/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_ratio_path(@ratio)
'|
=< link_to 'Back', ratios_path