config/routes.rb
Rails.application.routes.draw do
  resources :crops
  resources :coconut1s
  resources :coffee1s
  resources :rice3s
  resources :rice2s
  resources :rice1s
  root to: 'crops#index'
  devise_for :users
  resources :plants
  resources :ratios  
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :country, optional: true
  belongs_to :province, optional: true
  belongs_to :user, optional: true
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  def index
    @plants = Plant.all
  end

  def show
  end

  def new
    @plant = Plant.new
  end

  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      params.fetch(:plant, {})
    end
end

app/views/plants/_form.html.slim
= form_for @plant do |f|
  - if @plant.errors.any?
    #error_explanation
      h2 = "#{pluralize(@plant.errors.count, "error")} prohibited this plant from being saved:"
      ul
        - @plant.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/plants/_plant.html.slim
/- ye

.card.shadow.zoom-xs.mb-3
  = link_to plant
    .text-center
      = image_tag plant.photo, class: "img-fluid rounded"
    .card-footer.text-muted
      h4 
      .small
        .d-flex.justify-content-end.flex-wrap.pb-2
          = plant.name
          br
          = plant.name

          /- if plant.currency_price.present?
            .pr-2
              | #{t 'money.set price'} #{number_to_currency(item.currency_price, unit: "#{item.currency} ")} 
      .text-right
        small = plant.updated_at.strftime("%m/%d/%y at %l:%M %p")
        

app/views/plants/edit.html.slim
h1 Editing plant

== render 'form'

=> link_to 'Show', @plant
'|
=< link_to 'Back', plants_path

app/views/plants/index.html.slim
.px-4
  .row
    .col-12.col-lg-3
      .pt-3.pb-1
        h1 = t 'helpers.animals'
      .pb-2
      // FILTER BUTTONS
      .pb-2.d-flex.justify-content-between.flex-wrap
    // HALF    
    .col-12.col-lg-9
      .card-columns
        = render @plants
      

app/views/plants/new.html.slim
h1 New plant

== render 'form'

= link_to 'Back', plants_path

app/views/plants/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_plant_path(@plant)
'|
=< link_to 'Back', plants_path