config/routes.rb
Rails.application.routes.draw do
  resources :crops
  resources :coconut1s
  resources :coffee1s
  resources :rice3s
  resources :rice2s
  resources :rice1s
  root to: 'crops#index'
  devise_for :users
  resources :plants
  resources :ratios  
end

app/models/crop.rb
class Crop < ApplicationRecord
  belongs_to :country
  belongs_to :province
  belongs_to :category
  has_many :rice1s
  has_many :rice2s
  has_many :rice3s
  has_many :coffee1s
  has_many :coconut1s
end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
  before_action :set_crop, only: [:show, :edit, :update, :destroy]

  # GET /crops
  # GET /crops.json
  def index
    @crops = Crop.all
  end

  # GET /crops/1
  # GET /crops/1.json
  def show
  end

  # GET /crops/new
  def new
    @crop = Crop.new
  end

  # GET /crops/1/edit
  def edit
  end

  # POST /crops
  # POST /crops.json
  def create
    @crop = Crop.new(crop_params)

    respond_to do |format|
      if @crop.save
        format.html { redirect_to @crop, notice: 'Crop was successfully created.' }
        format.json { render :show, status: :created, location: @crop }
      else
        format.html { render :new }
        format.json { render json: @crop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crops/1
  # PATCH/PUT /crops/1.json
  def update
    respond_to do |format|
      if @crop.update(crop_params)
        format.html { redirect_to @crop, notice: 'Crop was successfully updated.' }
        format.json { render :show, status: :ok, location: @crop }
      else
        format.html { render :edit }
        format.json { render json: @crop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crops/1
  # DELETE /crops/1.json
  def destroy
    @crop.destroy
    respond_to do |format|
      format.html { redirect_to crops_url, notice: 'Crop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crop
      @crop = Crop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crop_params
      params.fetch(:crop, {})
    end
end

app/views/crops/edit.html.slim
h1 Editing crop

== render 'form'

=> link_to 'Show', @crop
'|
=< link_to 'Back', crops_path

app/views/crops/index.html.slim
.px-4
  .row
    .col-12.col-lg-3
      .pt-3.pb-1
        h1 SUPRICe Crops database
      .pb-2
      .pb-2.d-flex.justify-content-between.flex-wrap
    // HALF    
    .col-12.col-lg-9
      .card-columns
        .card.shadow.zoom-xs.mb-3
          = link_to rice1s_path
            .text-center
              = image_tag Crop.first.photo, class: "img-fluid rounded"
            .card-footer.text-muted
              h4
              .small
                .d-flex.justify-content-end.flex-wrap.pb-2
                  .pr-2
                    = Crop.first.name
                  .pr-2
                    = Crop.first.shortname                      
                  .pr-2
                    = Crop.first.country.name
                  .pr-2
                    = Crop.first.province.name
                  .pr-2
                    = Crop.first.category.name
        .card.shadow.zoom-xs.mb-3
          = link_to rice2s_path
            .text-center
              = image_tag Crop.second.photo, class: "img-fluid rounded"
            .card-footer.text-muted
              h4
              .small
                .d-flex.justify-content-end.flex-wrap.pb-2
                  .pr-2
                    = Crop.second.name
                  .pr-2
                    = Crop.second.shortname                      
                  .pr-2
                    = Crop.second.country.name
                  .pr-2
                    = Crop.second.province.name
                  .pr-2
                    = Crop.second.category.name
        .card.shadow.zoom-xs.mb-3
          = link_to rice3s_path
            .text-center
              = image_tag Crop.third.photo, class: "img-fluid rounded"
            .card-footer.text-muted
              h4
              .small
                .d-flex.justify-content-end.flex-wrap.pb-2
                  .pr-2
                    = Crop.third.name
                  .pr-2
                    = Crop.third.shortname                      
                  .pr-2
                    = Crop.third.country.name
                  .pr-2
                    = Crop.third.province.name
                  .pr-2
                    = Crop.third.category.name
        .card.shadow.zoom-xs.mb-3
          = link_to coconut1s_path
            .text-center
              = image_tag Crop.fourth.photo, class: "img-fluid rounded"
            .card-footer.text-muted
              h4
              .small
                .d-flex.justify-content-end.flex-wrap.pb-2
                  .pr-2
                    = Crop.fourth.name
                  .pr-2
                    = Crop.fourth.shortname                      
                  .pr-2
                    = Crop.fourth.country.name
                  .pr-2
                    = Crop.fourth.province.name
                  .pr-2
                    = Crop.fourth.category.name
        .card.shadow.zoom-xs.mb-3
          = link_to coffee1s_path
            .text-center
              = image_tag Crop.fifth.photo, class: "img-fluid rounded"
            .card-footer.text-muted
              h4
              .small
                .d-flex.justify-content-end.flex-wrap.pb-2
                  .pr-2
                    = Crop.fifth.name
                  .pr-2
                    = Crop.fifth.shortname                      
                  .pr-2
                    = Crop.fifth.country.name
                  .pr-2
                    = Crop.fifth.province.name
                  .pr-2
                    = Crop.fifth.category.name                                        
        

        /- @crops.each do |c|
          .card.shadow.zoom-xs.mb-3
            = link_to c
              .text-center
                = image_tag c.photo, class: "img-fluid rounded"
              .card-footer.text-muted
                h4
                .small
                  .d-flex.justify-content-end.flex-wrap.pb-2
                    .pr-2
                      = c.name
                    .pr-2
                      = c.shortname                      
                    .pr-2
                      = c.country.name
                    .pr-2
                      = c.province.name
                    .pr-2
                      = c.category.name

app/views/crops/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_crop_path(@crop)
'|
=< link_to 'Back', crops_path